steps:
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']
images:
- 'gcr.io/$PROJECT_ID/gcpdevops'
serviceAccount: '752544134273-compute@developer.gserviceaccount.com'
logsBucket: 'gs://devops-abib-project'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
logging: CLOUD_LOGGING_ONLY